using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace aula8.Migrations
{
    /// <inheritdoc />
    public partial class V2_BookTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("" +
              "create TABLE books(" +
                "id bigint  NOT NULL   generated by default as identity PRIMARY KEY," +
                "autor varchar(100) NOT NULL," +
                "titulo varchar(80) NOT NULL," +
                "valor decimal(38,2) NOT NULL," +
                   "data timestamp NOT NULL" +
                   ")");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
