using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace aula8.Migrations
{
    /// <inheritdoc />
    public partial class V1_PersonTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("" +
                "create TABLE PERSON(\r\n\t" +
                "id bigint  NOT NULL   generated by default as identity PRIMARY KEY,\r\n\t" +
                "address varchar(100) NOT NULL,\r\n\t" +
                "FIRST_NAME varchar(80) NOT NULL,\r\n\t" +
                "GENDER varchar(6) NOT NULL,\r\n\t" +
                "LAST_NAME VARCHAR(80) NOT NULL\r\n);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
          
        }
    }
}
